# Generated by Django 4.2.6 on 2024-02-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequisites',
            name='course',
        ),
        migrations.DeleteModel(
            name='Learning',
        ),
        migrations.DeleteModel(
            name='Prerequisites',
        ),
    ]
