# Generated by Django 4.2.6 on 2024-02-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0003_remove_prerequisites_course_delete_learning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
