# Generated by Django 4.2.6 on 2023-10-31 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0004_rename_videos_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
