# Generated by Django 4.2.6 on 2024-02-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0004_subject_description_subject_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(default='None', max_length=5000),
        ),
    ]
