# Generated by Django 4.2.6 on 2024-02-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0005_alter_subject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='users/images'),
        ),
    ]
