# Generated by Django 4.2.6 on 2024-02-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0006_alter_subject_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
