# Generated by Django 4.2.6 on 2024-02-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0008_remove_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
