# Generated by Django 4.2.6 on 2023-11-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0009_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='serial_number',
            field=models.IntegerField(unique=True),
        ),
    ]
