# Generated by Django 4.2.6 on 2024-02-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0009_subject_slug2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='slug2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
