# Generated by Django 4.2.6 on 2023-11-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0010_alter_video_serial_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='slug',
            new_name='slug2',
        ),
        migrations.AddField(
            model_name='video',
            name='video_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='serial_number',
            field=models.IntegerField(default=999, unique=True),
        ),
    ]
