# Generated by Django 4.2.6 on 2024-02-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0010_alter_subject_slug2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='slug2',
            new_name='slug3',
        ),
    ]
