# Generated by Django 4.2.6 on 2024-02-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0011_rename_slug2_video_slug3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='thumbnail',
            field=models.ImageField(upload_to='user/images'),
        ),
    ]
