# Generated by Django 4.2.6 on 2024-02-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0012_alter_subject_description_alter_subject_slug2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='user/images'),
        ),
    ]
