# Generated by Django 4.2.6 on 2023-11-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0013_delete_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
