# Generated by Django 4.2.6 on 2024-02-09 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0013_alter_subject_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_url',
            new_name='video_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_number',
        ),
    ]
