# Generated by Django 4.2.6 on 2023-11-01 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0015_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug2', models.CharField(max_length=100, null=True)),
                ('serial_number', models.IntegerField(default=999, unique=True)),
                ('video_number', models.IntegerField(default=0)),
                ('video_url', models.CharField(default=0, max_length=150)),
                ('is_preview', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resources.course')),
                ('subject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Resources.subject')),
            ],
        ),
    ]
